Algoritmo "Exercício 6"
// Disciplina   : Algoritmos e programção
// Professor    : Diogenes
// Descrição   : Código para fazer a conversão de Fahrenheit para Celsius
// Autor(a)    : Thiago Vinicius Szejka
// Data atual  : 14/10/2025


Var


temperatura_F: real

F_em_C: real

Inicio

escreva("Digite o valor da temperatura em F°: ")

leia(temperatura_F)

F_em_C <- (5*temperatura_F - 160)/9


escreva("A temperatura em °C é:")

escreval(F_em_C)


Fimalgoritmo
