Algoritmo "Exercício 13"
// Disciplina   : Algoritmos e programção
// Professor    : Diogenes
// Descrição   : Código para usar váriaveis internas
// Autor(a)    : Thiago Vinicius Szejka
// Data atual  : 21/10/2025
Var
x: real
Inicio

escreva("Digite x: ")
leia(x)

se 10 < x < 35 entao
   escreval("X está dentro da condição")
senao entao
   escreval("X não está dentro da condição")
fimse



Fimalgoritmo