Algoritmo "Exercício 13"
// Disciplina   : Algoritmos e programação
// Professor    : Diogenes
// Descrição    : Código para veficar se a variável está dentro da condição
// Autor(a)     : Thiago Vinicius Szejka
// Data atual   : 28/10/2025

Var
   x: real

Inicio
   escreva("Digite x: ")
   leia(x)

   se (x > 10) e (x < 35) entao
      escreval("X está dentro da condição")
   senao
      escreval("X não está dentro da condição")
   fimse

Fimalgoritmo

Fimalgoritmo
